const navLinks = [
  { path: "/", label: "Front Page" },
  { path: "/science", label: "Genius & Folly" },
  { path: "/life", label: "Human Currents" },
  { path: "/earth", label: "The Living Planet" },
  { path: "/finance", label: "Money & Madness" },
  { path: "/entertainment", label: "Arena of Fame" },
  { path: "/legacy", label: "Time Capsule" },
];

export default navLinks;

type Country = {
  code: string;
  name: string;
  flag: string;
};

export const countryData: Country[] = [
  { code: "AFN", name: "Afghanistan", flag: "af" },
  { code: "ALL", name: "Albania", flag: "al" },
  { code: "DZD", name: "Algeria", flag: "dz" },
  { code: "USD", name: "American Samoa", flag: "as" },
  { code: "EUR", name: "Andorra", flag: "ad" },
  { code: "AOA", name: "Angola", flag: "ao" },
  { code: "XCD", name: "Anguilla", flag: "ai" },
  { code: "XCD", name: "Antigua and Barbuda", flag: "ag" },
  { code: "ARS", name: "Argentina", flag: "ar" },
  { code: "AMD", name: "Armenia", flag: "am" },
  { code: "AWG", name: "Aruba", flag: "aw" },
  { code: "AUD", name: "Australia", flag: "au" },
  { code: "EUR", name: "Austria", flag: "at" },
  { code: "AZN", name: "Azerbaijan", flag: "az" },
  { code: "BSD", name: "Bahamas", flag: "bs" },
  { code: "BHD", name: "Bahrain", flag: "bh" },
  { code: "BDT", name: "Bangladesh", flag: "bd" },
  { code: "BBD", name: "Barbados", flag: "bb" },
  { code: "BYN", name: "Belarus", flag: "by" },
  { code: "EUR", name: "Belgium", flag: "be" },
  { code: "BZD", name: "Belize", flag: "bz" },
  { code: "XOF", name: "Benin", flag: "bj" },
  { code: "BMD", name: "Bermuda", flag: "bm" },
  { code: "BTN", name: "Bhutan", flag: "bt" },
  { code: "BOB", name: "Bolivia", flag: "bo" },
  { code: "BAM", name: "Bosnia and Herzegovina", flag: "ba" },
  { code: "BWP", name: "Botswana", flag: "bw" },
  { code: "BRL", name: "Brazil", flag: "br" },
  { code: "USD", name: "British Indian Ocean Territory", flag: "io" },
  { code: "BND", name: "Brunei", flag: "bn" },
  { code: "BGN", name: "Bulgaria", flag: "bg" },
  { code: "XOF", name: "Burkina Faso", flag: "bf" },
  { code: "BIF", name: "Burundi", flag: "bi" },
  { code: "CVE", name: "Cape Verde", flag: "cv" },
  { code: "KHR", name: "Cambodia", flag: "kh" },
  { code: "XAF", name: "Cameroon", flag: "cm" },
  { code: "CAD", name: "Canada", flag: "ca" },
  { code: "XAF", name: "Central African Republic", flag: "cf" },
  { code: "XAF", name: "Chad", flag: "td" },
  { code: "CLP", name: "Chile", flag: "cl" },
  { code: "CNY", name: "China", flag: "cn" },
  { code: "AUD", name: "Christmas Island", flag: "cx" },
  { code: "AUD", name: "Cocos (Keeling) Islands", flag: "cc" },
  { code: "COP", name: "Colombia", flag: "co" },
  { code: "KMF", name: "Comoros", flag: "km" },
  { code: "XAF", name: "Congo", flag: "cg" },
  { code: "CDF", name: "Democratic Republic of the Congo", flag: "cd" },
  { code: "NZD", name: "Cook Islands", flag: "ck" },
  { code: "CRC", name: "Costa Rica", flag: "cr" },
  { code: "XOF", name: "Côte d'Ivoire", flag: "ci" },
  { code: "HRK", name: "Croatia", flag: "hr" },
  { code: "CUP", name: "Cuba", flag: "cu" },
  { code: "ANG", name: "Curaçao", flag: "cw" },
  { code: "EUR", name: "Cyprus", flag: "cy" },
  { code: "CZK", name: "Czech Republic", flag: "cz" },
  { code: "DKK", name: "Denmark", flag: "dk" },
  { code: "DJF", name: "Djibouti", flag: "dj" },
  { code: "XCD", name: "Dominica", flag: "dm" },
  { code: "DOP", name: "Dominican Republic", flag: "do" },
  { code: "USD", name: "Ecuador", flag: "ec" },
  { code: "EGP", name: "Egypt", flag: "eg" },
  { code: "USD", name: "El Salvador", flag: "sv" },
  { code: "XAF", name: "Equatorial Guinea", flag: "gq" },
  { code: "ERN", name: "Eritrea", flag: "er" },
  { code: "EUR", name: "Estonia", flag: "ee" },
  { code: "ETB", name: "Ethiopia", flag: "et" },
  { code: "EUR", name: "European Union", flag: "eu" },
  { code: "FKP", name: "Falkland Islands", flag: "fk" },
  { code: "DKK", name: "Faroe Islands", flag: "fo" },
  { code: "FJD", name: "Fiji", flag: "fj" },
  { code: "EUR", name: "Finland", flag: "fi" },
  { code: "EUR", name: "France", flag: "fr" },
  { code: "EUR", name: "French Guiana", flag: "gf" },
  { code: "XPF", name: "French Polynesia", flag: "pf" },
  { code: "EUR", name: "French Southern Territories", flag: "tf" },
  { code: "XAF", name: "Gabon", flag: "ga" },
  { code: "GMD", name: "Gambia", flag: "gm" },
  { code: "GEL", name: "Georgia", flag: "ge" },
  { code: "EUR", name: "Germany", flag: "de" },
  { code: "GHS", name: "Ghana", flag: "gh" },
  { code: "GIP", name: "Gibraltar", flag: "gi" },
  { code: "EUR", name: "Greece", flag: "gr" },
  { code: "DKK", name: "Greenland", flag: "gl" },
  { code: "XCD", name: "Grenada", flag: "gd" },
  { code: "EUR", name: "Guadeloupe", flag: "gp" },
  { code: "USD", name: "Guam", flag: "gu" },
  { code: "GTQ", name: "Guatemala", flag: "gt" },
  { code: "GBP", name: "Guernsey", flag: "gg" },
  { code: "GNF", name: "Guinea", flag: "gn" },
  { code: "XOF", name: "Guinea-Bissau", flag: "gw" },
  { code: "GYD", name: "Guyana", flag: "gy" },
  { code: "HTG", name: "Haiti", flag: "ht" },
  { code: "AUD", name: "Heard Island and McDonald Islands", flag: "hm" },
  { code: "EUR", name: "Holy See", flag: "va" },
  { code: "HNL", name: "Honduras", flag: "hn" },
  { code: "HKD", name: "Hong Kong", flag: "hk" },
  { code: "HUF", name: "Hungary", flag: "hu" },
  { code: "ISK", name: "Iceland", flag: "is" },
  { code: "INR", name: "India", flag: "in" },
  { code: "IDR", name: "Indonesia", flag: "id" },
  { code: "IRR", name: "Iran", flag: "ir" },
  { code: "IQD", name: "Iraq", flag: "iq" },
  { code: "EUR", name: "Ireland", flag: "ie" },
  { code: "GBP", name: "Isle of Man", flag: "im" },
  { code: "ILS", name: "Israel", flag: "il" },
  { code: "EUR", name: "Italy", flag: "it" },
  { code: "JMD", name: "Jamaica", flag: "jm" },
  { code: "JPY", name: "Japan", flag: "jp" },
  { code: "GBP", name: "Jersey", flag: "je" },
  { code: "JOD", name: "Jordan", flag: "jo" },
  { code: "KZT", name: "Kazakhstan", flag: "kz" },
  { code: "KES", name: "Kenya", flag: "ke" },
  { code: "AUD", name: "Kiribati", flag: "ki" },
  { code: "KPW", name: "North Korea", flag: "kp" },
  { code: "KRW", name: "South Korea", flag: "kr" },
  { code: "KWD", name: "Kuwait", flag: "kw" },
  { code: "KGS", name: "Kyrgyzstan", flag: "kg" },
  { code: "LAK", name: "Laos", flag: "la" },
  { code: "EUR", name: "Latvia", flag: "lv" },
  { code: "LBP", name: "Lebanon", flag: "lb" },
  { code: "LSL", name: "Lesotho", flag: "ls" },
  { code: "LRD", name: "Liberia", flag: "lr" },
  { code: "LYD", name: "Libya", flag: "ly" },
  { code: "CHF", name: "Liechtenstein", flag: "li" },
  { code: "EUR", name: "Lithuania", flag: "lt" },
  { code: "EUR", name: "Luxembourg", flag: "lu" },
  { code: "MOP", name: "Macau", flag: "mo" },
  { code: "MKD", name: "North Macedonia", flag: "mk" },
  { code: "MGA", name: "Madagascar", flag: "mg" },
  { code: "MWK", name: "Malawi", flag: "mw" },
  { code: "MYR", name: "Malaysia", flag: "my" },
  { code: "MVR", name: "Maldives", flag: "mv" },
  { code: "XOF", name: "Mali", flag: "ml" },
  { code: "EUR", name: "Malta", flag: "mt" },
  { code: "USD", name: "Marshall Islands", flag: "mh" },
  { code: "EUR", name: "Martinique", flag: "mq" },
  { code: "MRU", name: "Mauritania", flag: "mr" },
  { code: "MUR", name: "Mauritius", flag: "mu" },
  { code: "EUR", name: "Mayotte", flag: "yt" },
  { code: "MXN", name: "Mexico", flag: "mx" },
  { code: "USD", name: "Micronesia", flag: "fm" },
  { code: "MDL", name: "Moldova", flag: "md" },
  { code: "EUR", name: "Monaco", flag: "mc" },
  { code: "MNT", name: "Mongolia", flag: "mn" },
  { code: "EUR", name: "Montenegro", flag: "me" },
  { code: "XCD", name: "Montserrat", flag: "ms" },
  { code: "MAD", name: "Morocco", flag: "ma" },
  { code: "MZN", name: "Mozambique", flag: "mz" },
  { code: "MMK", name: "Myanmar", flag: "mm" },
  { code: "NAD", name: "Namibia", flag: "na" },
  { code: "AUD", name: "Nauru", flag: "nr" },
  { code: "NPR", name: "Nepal", flag: "np" },
  { code: "EUR", name: "Netherlands", flag: "nl" },
  { code: "XPF", name: "New Caledonia", flag: "nc" },
  { code: "NZD", name: "New Zealand", flag: "nz" },
  { code: "NIO", name: "Nicaragua", flag: "ni" },
  { code: "XOF", name: "Niger", flag: "ne" },
  { code: "NGN", name: "Nigeria", flag: "ng" },
  { code: "NZD", name: "Niue", flag: "nu" },
  { code: "AUD", name: "Norfolk Island", flag: "nf" },
  { code: "USD", name: "Northern Mariana Islands", flag: "mp" },
  { code: "NOK", name: "Norway", flag: "no" },
  { code: "OMR", name: "Oman", flag: "om" },
  { code: "PKR", name: "Pakistan", flag: "pk" },
  { code: "USD", name: "Palau", flag: "pw" },
  { code: "ILS", name: "Palestine", flag: "ps" },
  { code: "PAB", name: "Panama", flag: "pa" },
  { code: "PGK", name: "Papua New Guinea", flag: "pg" },
  { code: "PYG", name: "Paraguay", flag: "py" },
  { code: "PEN", name: "Peru", flag: "pe" },
  { code: "PHP", name: "Philippines", flag: "ph" },
  { code: "NZD", name: "Pitcairn Islands", flag: "pn" },
  { code: "PLN", name: "Poland", flag: "pl" },
  { code: "EUR", name: "Portugal", flag: "pt" },
  { code: "USD", name: "Puerto Rico", flag: "pr" },
  { code: "QAR", name: "Qatar", flag: "qa" },
  { code: "EUR", name: "Réunion", flag: "re" },
  { code: "RON", name: "Romania", flag: "ro" },
  { code: "RUB", name: "Russia", flag: "ru" },
  { code: "RWF", name: "Rwanda", flag: "rw" },
  { code: "EUR", name: "Saint Barthélemy", flag: "bl" },
  { code: "SHP", name: "Saint Helena", flag: "sh" },
  { code: "XCD", name: "Saint Kitts and Nevis", flag: "kn" },
  { code: "XCD", name: "Saint Lucia", flag: "lc" },
  { code: "EUR", name: "Saint Martin", flag: "mf" },
  { code: "EUR", name: "Saint Pierre and Miquelon", flag: "pm" },
  { code: "XCD", name: "Saint Vincent and the Grenadines", flag: "vc" },
  { code: "WST", name: "Samoa", flag: "ws" },
  { code: "EUR", name: "San Marino", flag: "sm" },
  { code: "STN", name: "São Tomé and Príncipe", flag: "st" },
  { code: "SAR", name: "Saudi Arabia", flag: "sa" },
  { code: "XOF", name: "Senegal", flag: "sn" },
  { code: "RSD", name: "Serbia", flag: "rs" },
  { code: "SCR", name: "Seychelles", flag: "sc" },
  { code: "SLL", name: "Sierra Leone", flag: "sl" },
  { code: "SGD", name: "Singapore", flag: "sg" },
  { code: "EUR", name: "Slovakia", flag: "sk" },
  { code: "EUR", name: "Slovenia", flag: "si" },
  { code: "SBD", name: "Solomon Islands", flag: "sb" },
  { code: "SOS", name: "Somalia", flag: "so" },
  { code: "ZAR", name: "South Africa", flag: "za" },
  { code: "GBP", name: "South Georgia and South Sandwich Islands", flag: "gs" },
  { code: "SSP", name: "South Sudan", flag: "ss" },
  { code: "EUR", name: "Spain", flag: "es" },
  { code: "LKR", name: "Sri Lanka", flag: "lk" },
  { code: "SDG", name: "Sudan", flag: "sd" },
  { code: "SRD", name: "Suriname", flag: "sr" },
  { code: "NOK", name: "Svalbard and Jan Mayen", flag: "sj" },
  { code: "SZL", name: "Eswatini", flag: "sz" },
  { code: "SEK", name: "Sweden", flag: "se" },
  { code: "CHF", name: "Switzerland", flag: "ch" },
  { code: "SYP", name: "Syria", flag: "sy" },
  { code: "TWD", name: "Taiwan", flag: "tw" },
  { code: "TJS", name: "Tajikistan", flag: "tj" },
  { code: "TZS", name: "Tanzania", flag: "tz" },
  { code: "THB", name: "Thailand", flag: "th" },
  { code: "USD", name: "Timor-Leste", flag: "tl" },
  { code: "XOF", name: "Togo", flag: "tg" },
  { code: "NZD", name: "Tokelau", flag: "tk" },
  { code: "TOP", name: "Tonga", flag: "to" },
  { code: "TTD", name: "Trinidad and Tobago", flag: "tt" },
  { code: "TND", name: "Tunisia", flag: "tn" },
  { code: "TRY", name: "Turkey", flag: "tr" },
  { code: "TMT", name: "Turkmenistan", flag: "tm" },
  { code: "USD", name: "Turks and Caicos Islands", flag: "tc" },
  { code: "AUD", name: "Tuvalu", flag: "tv" },
  { code: "UGX", name: "Uganda", flag: "ug" },
  { code: "UAH", name: "Ukraine", flag: "ua" },
  { code: "AED", name: "United Arab Emirates", flag: "ae" },
  { code: "GBP", name: "United Kingdom", flag: "gb" },
  { code: "USD", name: "United States", flag: "us" },
  { code: "UYU", name: "Uruguay", flag: "uy" },
  { code: "UZS", name: "Uzbekistan", flag: "uz" },
  { code: "VUV", name: "Vanuatu", flag: "vu" },
  { code: "VES", name: "Venezuela", flag: "ve" },
  { code: "VND", name: "Vietnam", flag: "vn" },
  { code: "USD", name: "Virgin Islands, British", flag: "vg" },
  { code: "USD", name: "Virgin Islands, U.S.", flag: "vi" },
  { code: "XPF", name: "Wallis and Futuna", flag: "wf" },
  { code: "MAD", name: "Western Sahara", flag: "eh" },
  { code: "YER", name: "Yemen", flag: "ye" },
  { code: "ZMW", name: "Zambia", flag: "zm" },
  { code: "ZWL", name: "Zimbabwe", flag: "zw" },
];

export const getCountryName = (countryCode: string): string => {
  // Convert countryCode to uppercase for comparison
  const upperCode = countryCode.toUpperCase();

  // Find the country by flag code
  const found = countryData.find((c) => c.flag.toUpperCase() === upperCode);

  return found ? found.name : countryCode;
};
